[package]
name = "oak-core"
description = "Core parser combinator library providing fundamental parsing primitives."
categories = ["parsing", "no-std"]
keywords = ["parser", "parser-combinators", "core", "primitive"]
documentation = "https://docs.rs/oak-core"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
walkdir = { workspace = true, optional = true }
schemars = { workspace = true }
lsp-types = { version = "0.97.0" }
url = { version = "2.5.7" }
triomphe = { version = "0.1.15", default-features = false }
tracing = { version = "0.1.*" }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }
serde_json = { workspace = true }
walkdir = { workspace = true }

[features]
default = []
testing = ["walkdir", "serde_json"]

[package.metadata.docs.rs]
all-features = true
