[package]
name = "oak-core"
version.workspace = true
authors.workspace = true
description = "Core parser combinator library providing fundamental parsing primitives."
edition.workspace = true
license.workspace = true
readme = "readme.md"
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-core"
documentation = "https://docs.rs/oak-core"
categories = ["parsing", "no-std"]
keywords = ["parser", "parser-combinators", "core", "primitive"]

[dependencies]
serde = { workspace = true, optional = true }
triomphe = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]

[features]
default = []
serde = ["dep:serde"]
testing = []

[package.metadata.docs.rs]
all-features = true
