[package]
name = "oak-core"
description = "Core parser combinator library providing fundamental parsing primitives."
categories = ["parsing", "no-std"]
keywords = ["parser", "parser-combinators", "core", "primitive"]
documentation = "https://docs.rs/oak-core"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
triomphe = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]

[features]
default = []
serde = ["dep:serde"]
testing = []

[package.metadata.docs.rs]
all-features = true
