[package]
name = "oak-pretty-print"
description = "Syntax highlighter supporting multiple programming languages."
categories = ["text-processing"]
keywords = ["syntax-highlighting", "code", "highlighting", "multi-language"]
documentation = "https://docs.rs/oak-pretty-print"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true, features = ["serde"] }
oak-macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
oak-testing = { workspace = true }


[features]
default = []


[package.metadata.docs.rs]
all-features = true
