[package]
name = "oak-pretty-print"
version.workspace = true
authors.workspace = true
description = "Syntax highlighter supporting multiple programming languages."
edition.workspace = true
license.workspace = true
readme = "readme.md"
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-pretty-print"
documentation = "https://docs.rs/oak-pretty-print"
categories = ["text-processing"]
keywords = ["syntax-highlighting", "code", "highlighting", "multi-language"]

[dependencies]
oak-core = { workspace = true, features = ["serde"] }
oak-macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = []

[package.metadata.docs.rs]
all-features = true
