[package]
name = "oak-folding"
version.workspace = true
authors.workspace = true
description = "Code folding logic and AST-based region detection for the Oak framework."
edition.workspace = true
license.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-folding"
categories = ["development-tools"]
keywords = ["folding", "code-folding", "ast"]

[dependencies]
oak-core = { workspace = true, features = ["serde"] }
serde = { workspace = true }
