[package]
name = "oak-twig"
description = "Twig templating engine parser with support for modern template syntax and features."
categories = ["parsing"]
keywords = ["parser", "twig", "template", "templating"]
documentation = "https://docs.rs/oak-twig"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true, features = ["serde", "testing"] }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
oak-lsp = { workspace = true }
oak-mcp = { workspace = true, features = ["io-std"] }
oak-hover = { workspace = true }
oak-vfs = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = []
std = []


[package.metadata.docs.rs]
all-features = true
