[package]
name = "oak-wgsl"
description = "WGSL language parser with support for modern shader programming and WebGPU features."
categories = ["parsing"]
keywords = ["parser", "wgsl", "shader", "webgpu"]
documentation = "https://docs.rs/oak-wgsl"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
oak-testing = { workspace = true }


[features]
default = []


[package.metadata.docs.rs]
all-features = true
