[package]
name = "oak-highlight"
version.workspace = true
authors.workspace = true
description = "A lightweight syntax highlighter for Rust with support for multiple programming languages and customizable themes."
edition.workspace = true
license.workspace = true
readme = "readme.md"
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-highlight"
documentation = "https://docs.rs/oak-highlight"
categories = ["text-processing"]
keywords = ["syntax-highlighting", "code-highlighting", "multi-language", "rust"]

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
oak-testing = { workspace = true }
oak-rust = { workspace = true }

[features]
default = []

[package.metadata.docs.rs]
all-features = true
