[package]
name = "oak-lsp"
description = "Lightweight LSP types for the Oak framework"
categories = ["development-tools"]
keywords = ["lsp", "language-server", "types"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0"
serde = { workspace = true }
futures = "0.3"
dashmap = "5.5"
url = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true }
oak-folding = { workspace = true }
axum = { workspace = true, optional = true }
actix-web = { workspace = true, optional = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-util", "io-std", "macros", "sync"] }
tower-lsp = { workspace = true, optional = true }

[features]
default = []
axum = ["dep:axum"]
actix-web = ["dep:actix-web"]
tower-lsp = ["dep:tower-lsp"]
