[package]
name = "oak-perl"
description = "High-performance incremental Perl parser for the oak ecosystem with flexible configuration."
categories = ["parsing"]
keywords = ["parser", "perl", "regex", "text-processing"]
documentation = "https://docs.rs/oak-perl"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
serde = { workspace = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = []


[package.metadata.docs.rs]
all-features = true