[package]
name = "oak-nginx"
description = "High-performance incremental Nginx configuration parser for the oak ecosystem with flexible configuration, optimized for web server configuration and routing processing."
categories = ["parsing"]
keywords = ["parser", "nginx", "configuration", "web-server"]
documentation = "https://docs.rs/oak-nginx"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = []
alloc = []

[package.metadata.docs.rs]
all-features = true