[package]
name = "oak-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
categories = ["compilers", "development-tools"]
keywords = ["frontend", "language", "python"]
description = "Hand-written Python frontend"

[dependencies]
oak-core = { workspace = true, features = ["serde"] }
oak-highlight = { workspace = true }
oak-pretty-print = { workspace = true }
oak-lsp = { workspace = true }
oak-hover = { workspace = true }
oak-vfs = { workspace = true }
oak-mcp = { workspace = true, features = ["io-std"] }
serde = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = []
std = []
