[package]
name = "oak-matlab"
description = "High-performance incremental MATLAB parser for the oak ecosystem with flexible configuration, optimized for scientific computing and data analysis."
categories = ["parsing"]
keywords = ["parser", "matlab", "scientific", "computing"]
documentation = "https://docs.rs/oak-matlab"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = []
alloc = []

[package.metadata.docs.rs]
all-features = true