[package]
name = "oak-typescript"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
categories = ["compilers", "development-tools"]
keywords = ["frontend", "language", "typescript"]
description = "TypeScript frontend for Oak"

[dependencies]
oak-core = { workspace = true }
oak-lsp = { workspace = true }
oak-vfs = { workspace = true }
oak-mcp = { workspace = true, optional = true }
serde = { workspace = true }
# serde_json = { workspace = true } # replaced by oak-json
oak-json = { workspace = true }
tokio = { workspace = true, optional = true }

[features]
default = ["mcp"]
mcp = ["dep:oak-mcp", "oak-mcp/io-std"]
semantic-search = []
