[package]
name = "oak-typescript"
version.workspace = true
authors.workspace = true
description = "TypeScript frontend for Oak"
edition.workspace = true
license.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/examples/oak-typescript"
categories = ["compilers", "development-tools"]
keywords = ["frontend", "language", "typescript"]

[dependencies]
oak-core = { workspace = true }
oak-lsp = { workspace = true, optional = true }
oak-vfs = { workspace = true, optional = true }
oak-mcp = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
# serde_json = { workspace = true } # replaced by oak-json
oak-json = { workspace = true }
tokio = { workspace = true, optional = true }

oak-hover = { workspace = true, optional = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
futures = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]
oak-highlight = ["dep:oak-highlight"]
oak-pretty-print = ["dep:oak-pretty-print"]
lsp = ["dep:oak-lsp", "dep:oak-hover", "dep:oak-vfs", "oak-highlight", "oak-pretty-print", "dep:futures"]
mcp = ["lsp", "oak-mcp/io-std"]

[dev-dependencies]
oak-testing = { workspace = true }
lazy_static = { workspace = true }
