[package]
name = "oak-structurizr"
version.workspace = true
authors.workspace = true
description = "Structurizr DSL parser for Oak"
edition.workspace = true
license.workspace = true
readme = "readme.md"
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/examples/oak-structurizr"

[dependencies]
oak-core = { workspace = true }
oak-c4 = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
oak-lsp = { workspace = true, optional = true }
oak-hover = { workspace = true, optional = true }
oak-vfs = { workspace = true, optional = true }
oak-mcp = { workspace = true, optional = true, features = ["io-std"] }
serde = { workspace = true, optional = true }
tracing = { workspace = true }
tokio = { workspace = true, optional = true }
futures = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde", "oak-c4/serde"]
oak-highlight = ["dep:oak-highlight"]
oak-pretty-print = ["dep:oak-pretty-print"]
lsp = ["dep:oak-lsp", "dep:oak-hover", "dep:oak-vfs", "oak-highlight", "oak-pretty-print", "dep:futures"]
mcp = ["lsp", "oak-mcp/io-std"]
