[package]
name = "oak-visualize"
version.workspace = true
authors.workspace = true
description = "High-performance visualization and layout algorithms for the oak ecosystem with flexible configuration, emphasizing tree and graph visualization."
edition.workspace = true
license.workspace = true
readme = "readme.md"
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-visualize"
documentation = "https://docs.rs/oak-visualize"
categories = ["visualization", "algorithms"]
keywords = ["visualization", "layout", "ast", "tree", "graph"]

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
oak-testing = { workspace = true }
oak-json = { workspace = true }

[features]
default = []
