[package]
name = "oak-json"
description = "High-performance incremental JSON parser for the oak ecosystem with flexible configuration, optimized for data interchange and configuration files."
categories = ["parsing"]
keywords = ["parser", "json", "streaming", "validation"]
documentation = "https://docs.rs/oak-json"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }
triomphe = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
oak-lsp = { workspace = true }
oak-hover = { workspace = true }
oak-vfs = { workspace = true }
oak-mcp = { workspace = true, optional = true }
serde = { workspace = true }
futures = { workspace = true }
axum = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }
oak-macros = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
mcp = ["dep:oak-mcp"]
axum = ["mcp", "dep:tokio", "dep:axum", "oak-mcp/axum", "oak-lsp/axum"]


[package.metadata.docs.rs]
all-features = true
