[package]
name = "oak-vhdl"
description = "VHDL language parser with support for hardware description and digital circuit design."
categories = ["parsing", "hardware-support"]
keywords = ["parser", "vhdl", "hardware", "hdl", "digital-circuit"]
documentation = "https://docs.rs/oak-vhdl"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
oak-core = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = []


[package.metadata.docs.rs]
all-features = true
