[package]
name = "oak-testing"
version.workspace = true
authors.workspace = true
description = "Testing utilities for the Oak language toolchain."
edition.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-testing"

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
triomphe = { workspace = true }
walkdir = { workspace = true }
