[package]
name = "oak-testing"
version.workspace = true
description = "Testing utilities for the Oak language toolchain."
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
triomphe = { workspace = true }
walkdir = { workspace = true }
