[package]
name = "oak-org-mode"
description = "Org-mode parser with support for Emacs org-mode syntax and features."
categories = ["parsing"]
keywords = ["parser", "org-mode", "emacs", "documentation"]
documentation = "https://docs.rs/oak-org-mode"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true }
oak-pretty-print = { workspace = true }
oak-lsp = { workspace = true }
oak-hover = { workspace = true }
oak-vfs = { workspace = true }
oak-mcp = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }

tokio = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = []
io-std = ["oak-mcp/io-std", "dep:tokio"]


[package.metadata.docs.rs]
all-features = true
