[package]
name = "oak-msil"
description = "High-performance incremental MSIL (Microsoft Intermediate Language) parser for the oak ecosystem with flexible configuration."
categories = ["parsing"]
keywords = ["parser", "msil", "cil", "dotnet", "assembly"]
documentation = "https://docs.rs/oak-msil"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = []
alloc = []

[package.metadata.docs.rs]
all-features = true