[package]
name = "oak-valkyrie"
description = "Valkyrie language parser with support for modern Valkyrie syntax and features."
categories = ["parsing"]
keywords = ["parser", "valkyrie", "language"]
documentation = "https://docs.rs/oak-valkyrie"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
oak-lsp = { workspace = true }
oak-mcp = { workspace = true, optional = true }
oak-hover = { workspace = true }
oak-vfs = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
unicode-ident = { workspace = true }
axum = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }
serde_json = { workspace = true }


[features]
default = ["mcp", "highlight", "pretty-print"]
mcp = ["dep:oak-mcp"]
axum = ["mcp", "dep:tokio", "dep:axum", "oak-mcp/axum", "oak-lsp/axum"]
highlight = ["dep:oak-highlight"]
pretty-print = ["dep:oak-pretty-print"]
std = []


[package.metadata.docs.rs]
all-features = true
