[package]
name = "oak-xml"
description = "High-performance incremental XML parser for the oak ecosystem with flexible configuration."
categories = ["parsing"]
keywords = ["parser", "xml", "markup", "document"]
documentation = "https://docs.rs/oak-xml"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true, features = ["serde"] }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
serde = { workspace = true }

[dev-dependencies]
oak-testing = { workspace = true }


[features]
default = []


[package.metadata.docs.rs]
all-features = true
