[package]
name = "oak-wit"
description = "WebAssembly Interface Types (WIT) component parser with support for interface definitions and component model."
categories = ["parsing"]
keywords = ["parser", "wit", "webassembly", "component-model"]
documentation = "https://docs.rs/oak-wit"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }

[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = []


[package.metadata.docs.rs]
all-features = true
