[package]
name = "oak-kotlin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
categories = ["compilers", "development-tools"]
keywords = ["frontend", "language", "kotlin"]
description = "Kotlin frontend for Oak"

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
oak-testing = { workspace = true }
