[package]
name = "oak-lua"
version = "0.0.3"
authors = ["Yggdrasill Team <192607617@qq.com>"]
description = "High-performance incremental Lua parser for the oak ecosystem with flexible configuration, supporting lightweight scripting and embedded development."
edition = "2024"
license = "MPL-2.0"
readme = "readme.md"
homepage = "https://github.com/ygg-lang/oaks"
repository = "https://github.com/ygg-lang/oaks/tree/master/examples/oak-lua"
documentation = "https://docs.rs/oak-lua"
categories = ["parsing"]
keywords = ["parser", "lua", "scripting", "language"]

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
oak-lsp = { workspace = true, optional = true }
oak-mcp = { workspace = true, optional = true }
oak-hover = { workspace = true, optional = true }
oak-vfs = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]
lsp = ["dep:oak-lsp", "dep:oak-hover", "dep:oak-vfs", "oak-highlight", "oak-pretty-print", "dep:futures"]
mcp = ["lsp", "oak-mcp/io-std"]

[package.metadata.docs.rs]
all-features = true
