[package]
name = "oak-pascal"
description = "High-performance incremental Pascal parser for the oak ecosystem with flexible configuration."
categories = ["parsing"]
keywords = ["parser", "pascal", "delphi", "ast"]
documentation = "https://docs.rs/oak-pascal"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }


[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }
serde_json = { workspace = true }

[features]
default = []


[package.metadata.docs.rs]
all-features = true