[package]
name = "oak-sass"
description = "High-performance incremental Sass parser for the oak ecosystem with flexible configuration, supporting CSS preprocessing and styling."
categories = ["parsing"]
keywords = ["parser", "sass", "css", "stylesheet"]
documentation = "https://docs.rs/oak-sass"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }


[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = ["alloc", "oak-highlight"]
alloc = []

[package.metadata.docs.rs]
all-features = true