[package]
name = "oak-sql"
description = "High-performance incremental SQL parser for the oak ecosystem with flexible configuration, optimized for database query processing and data manipulation."
categories = ["parsing"]
keywords = ["parser", "sql", "database", "query"]
documentation = "https://docs.rs/oak-sql"
readme = "readme.md"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }


[dev-dependencies]
oak-core = { workspace = true, features = ["testing"] }


[features]
default = ["alloc", "oak-highlight"]
alloc = []

[package.metadata.docs.rs]
all-features = true