[package]
name = "oak-repl"
version.workspace = true
authors.workspace = true
description = "Custom-built REPL infrastructure for Oak languages"
edition.workspace = true
license.workspace = true
readme = "readme.md"
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-repl"

[dependencies]
crossterm = { workspace = true }
unicode-width = { workspace = true }
clap = { workspace = true }
oak-highlight = { workspace = true }
oak-core = { workspace = true }
