[package]
name = "oak-diagnostic"
version.workspace = true
authors.workspace = true
description = "Beautiful diagnostic reporting for the Oak ecosystem, inspired by miette."
edition.workspace = true
license.workspace = true
homepage = "https://github.com/ygg-lang/oaks"
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-diagnostic"
categories = ["development-tools"]
keywords = ["diagnostic", "error", "reporting", "miette"]

[lib]
path = "src/lib.rs"

[dependencies]
oak-core = { workspace = true, features = ["serde"] }
oak-vfs = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
