name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  check:
    name: Check on ${{ matrix.os }}, ${{ matrix.feature_set.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        feature_set:
          - { name: "no Features", flags: "--no-default-features" }
          - { name: "default Features", flags: "" }
          - { name: "all Features", flags: "--all-features" }
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Cargo Check
        run: cargo check ${{ matrix.feature_set.flags }}
        env:
          RUSTFLAGS: -A warnings

  build:
    name: Build for ${{ matrix.os }}
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Build Release
        run: cargo build --release
        env:
          RUSTFLAGS: -A warnings
