name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Check Format
        run: cargo fmt --all -- --check

  lint:
    name: Lint on ${{ matrix.os }}, ${{ matrix.feature_set.name }}
    # Needed for crlf parsing check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        feature_set:
          - { name: "no features", flags: "--no-default-features" }
          - { name: "default features", flags: "" }
          - { name: "all features", flags: "--all-features" }
    steps:
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy ${{ matrix.feature_set.flags }} --all-targets -- -D warnings
        env:
          RUSTFLAGS: -A warnings

  test:
    name: Test on ${{ matrix.os }}
    needs: [format, lint]
    # Needed for platform-specific behavior testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Build Release
        run: cargo build --release
        env:
          RUSTFLAGS: -A warnings
      - name: Test Release
        run: cargo test --release
        env:
          RUSTFLAGS: -A warnings
